apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-finance-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-finance-app
  template:
    metadata:
      labels:
        app: bank-finance-app
    spec:
      containers:
      - name: bank-finance-app
        image: rameshkumarverma/bank-finance-app:latest 
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name:bank-finance-app-service
spec:
  selector:
    app: sbank-finance-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
